export enum HabitTypeEnum {
    Ernährung = "ernährung",
    Bewegung = "bewegung",
    Schlafhygiene = "schlafhygiene",
    Bildschirmzeit = "bildschirmzeit",
    SozialeMedien = "soziale_medien",
    Gaming = "gaming",
    Rauchen = "rauchen",
    Alkohol = "alkohol",
    Drogenkonsum = "drogenkonsum",
    Meditation = "meditation",
    Produktivität = "produktivität",
    Ausgaben = "ausgaben",
    Impulskontrolle = "impulskontrolle",
    Zuckeraufnahme = "zuckeraufnahme",
    Koffein = "koffein",
    Hygiene = "hygiene",
    Beziehungsverhalten = "beziehungsverhalten",
    Zeitmanagement = "zeitmanagement",
    Andere = "andere"    
}