export enum ObstacleTypeEnum {
    Zeitmangel = "zeitmangel",
    Stress = "stress",
    SozialeAnlässe = "soziale_anlaesse",
    Langeweile = "langeweile",
    Gewohnheit = "gewohnheit",
    Unbekannt = "unbekannt",
    Ablenkung = "ablenkung",
    MangelndeMotivation = "mangelnde_motivation",
    Müdigkeit = "muedigkeit",
    EmotionaleSituationen = "emotionale_situationen",
    SozialeSituationen = "soziale_situationen",
    Zweifel = "zweifel",
    FehlendeRessourcen = "fehlende_ressourcen",
    GesundheitlicheProbleme = "gesundheitliche_probleme",
    Wetter = "wetter",
    Keine = "keine",
}