export enum SideEffectTypeEnum {
    Keine = "keine",
    Uebelkeit = "übelkeit",
    Erbrechen = "erbrechen",
    Schwindel = "schwindel",
    Kopfschmerzen = "kopfschmerzen",
    TrockenerMund = "trockener_mund",
    RoteAugen = "rote_augen",
    Angst = "angst",
    Paranoia = "paranoia",
    Euphorie = "euphorie",
    Müdigkeit = "müdigkeit",
    Schwitzen = "schwitzen",
    ErhöhterPuls = "erhöhter_puls",
    VerringerterPuls = "verringerter_puls",
    Verwirrtheit = "verwirrtheit",
    EingeschränkteKoordination = "eingeschränkte_koordination",
    Gedächtnisprobleme = "gedächtnisprobleme",
    Appetitsteigerung = "appetitsteigerung",
    Appetitverringerung = "appetitverringerung",
    Unruhe = "unruhe",
    Schlaflosigkeit = "schlaflosigkeit",
    Muskelverspannung = "muskelverspannung",
    Frösteln = "frösteln",
    Andere = "andere"
}