export enum TriggerTypeEnum {
    Stress = "stress",
    Langeweile = "langeweile",
    SozialeSituationen = "soziale_situationen",
    EmotionaleSituationen = "emotionale_situationen",
    Gewohnheit = "gewohnheit",
    Unbekannt = "unbekannt",
    Erfolg = "erfolg",
    Freunde = "freunde",
    Familie = "familie",
    Arbeit = "arbeit",
    Schule = "schule",
    Freizeit = "freizeit",
    Müdigkeit = "muedigkeit",
    Angst = "angst",
    Freude = "freude",
    Traurigkeit = "traurigkeit",
    Natur = "natur",
    Hobby = "hobby",
}