export enum WorkoutTypeEnum {
  Mix = "mix",
  Krafttraining = "krafttraining",
  Ausdauertraining = "ausdauertraining",
  Yoga = "yoga",
  Hiit = "hiit",
  Pilates = "pilates",
  Crossfit = "crossfit",
  FunctionalTraining = "functional_training",
  CoreTraining = "core_training",
  Stretching = "stretching",
  Mobility = "mobility",
  Flexibility = "flexibility",
  Cardio = "cardio",
  Bodyweight = "bodyweight",
  Gewichtheben = "gewichtheben",
  Calisthenics = "calisthenics",
}
